service: my-express-application

provider:
  name: aws 
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

functions:
  extract-data:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'